name: 'Change Management'

on:
  pull_request:
    branches: [ "main" ]

jobs:
  resourcely-ci:
    runs-on: ubuntu-latest
    steps:

      - name: Install spacectl
        uses: spacelift-io/setup-spacectl@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy infrastructure
        env:
          SPACELIFT_API_KEY_ENDPOINT: https://darkmoon.app.spacelift.io
          SPACELIFT_API_KEY_ID: ${{ secrets.SPACELIFT_API_KEY_ID }}
          SPACELIFT_API_KEY_SECRET: ${{ secrets.SPACELIFT_API_KEY_SECRET }}
        run: spacectl stack list

      - name: Evaluate Code With Resourcely Guardrails
        shell: bash
        if: success()
        run: |
          echo 123
